version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess:5.3.1-alpine-edge
    #command: wait-for pingfederate:9031 -t 820 -- entrypoint.sh start-server
    command: entrypoint.sh start-server
    environment: 
      - SERVER_PROFILE_URL=https://github.com/ttranatping/salesu2020pingaccess.git
      - SERVER_PROFILE_PATH=server_profiles/pingaccess
      - OPERATIONAL_MODE=STANDALONE
      - PA_CONSOLE_HOST=pingaccess
      - INITIAL_ADMIN_PASSWORD=2FederateM0re
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in
    ports:
      - 443:3000
      - 9000:9000
    networks:
      - pingnet-dmz

  pingfederate:
    image: gcr.io/ping-identity/pingfederate:10.0.0-Beta-centos-edge
    #command: wait-for pingdirectory:389 -t 600 -- entrypoint.sh start-server
    command: entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/ttranatping/salesu2020pingaccess.git
      - SERVER_PROFILE_PATH=server_profiles/pingfederate
      - PF_BASE_URL=https://sso.pingapac.com
      - PF_REF_ADAPTER_ID=consentAdapter
      - PF_REF_ADAPTER_USERNAME=consentUsername
      - PF_REF_ADAPTER_PASSWORD=P@ssword1
      - SOFTWARE_STATEMENT_ACCC_ISSUER=cdr-register
      - SOFTWARE_STATEMENT_BANK_AUDIENCE=https://saidbank
      - USER_BASE_DN=dc=saidbank,dc=com,dc=au
      - OPERATIONAL_MODE=STANDALONE
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/ttranatping/salesu2020pingaccess.git
      - SERVER_PROFILE_PATH=server_profiles/pingdirectory
      - PF_BASE_HOST=sso-admin.pingapac.com
      - PF_BASE_PORT=443
      - DA_CLIENTID=admin_delegator
      - USER_BASE_DN=dc=saidbank,dc=com,dc=au
      - PINGFEDERATE_BACKCHANNEL_HOST=https://pingfederate:9031
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ports:
      - 636:636
      - 389:389
      - 2443:443
    networks:
      - pingnet-dmz
      - pingnet-internal
              
networks:
    pingnet-internal:
    pingnet-dmz:
